# Generated by Django 5.0.6 on 2024-07-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='usercontactno',
            field=models.CharField(max_length=12, verbose_name='Contact_No'),
        ),
    ]
