# Generated by Django 5.0.6 on 2024-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_test', models.DateField(auto_created=True, auto_now=True)),
                ('lname', models.CharField(max_length=200, verbose_name='Lab Assistance Name')),
                ('lab_name', models.CharField(max_length=200, verbose_name='lab name')),
                ('test_name', models.CharField(max_length=200, verbose_name='blood test name')),
                ('patientname', models.CharField(max_length=200, verbose_name='Patient name')),
                ('email', models.EmailField(max_length=200)),
                ('Haemoglobin', models.PositiveIntegerField(default='')),
                ('RBC_Count', models.PositiveIntegerField(default='')),
                ('PCV', models.PositiveIntegerField(default='')),
                ('MCV', models.PositiveIntegerField(default='')),
                ('MCH', models.PositiveIntegerField(default='')),
                ('MCHC', models.PositiveIntegerField(default='')),
                ('RDW', models.PositiveIntegerField(default='')),
                ('Total_WBC_Count', models.PositiveIntegerField(default='')),
                ('Neutrophils', models.PositiveIntegerField(default='')),
                ('Lymphocytes', models.PositiveIntegerField(default='')),
                ('Eosinophils', models.PositiveIntegerField(default='')),
                ('Monocytes', models.PositiveIntegerField(default='')),
                ('Basophils', models.PositiveIntegerField(default='')),
                ('Platelet_Count', models.PositiveIntegerField(default='')),
                ('WBCs_on_PS', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
