# Generated by Django 5.0.6 on 2024-07-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=200, verbose_name='Blood Test Name')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('schedule', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=12)),
                ('appointment_booked', models.BooleanField(default=False)),
                ('Test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryapp.name_category')),
            ],
        ),
    ]
