# Generated by Django 5.0.6 on 2024-07-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0002_name_category_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Test_name',
            new_name='test_name',
        ),
    ]
