# Generated by Django 5.0.6 on 2024-07-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0003_rename_test_name_appointment_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='test_name',
            new_name='Test_name',
        ),
    ]
