# Generated by Django 5.0.6 on 2024-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0006_rename_test_name_test_category_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lid', models.EmailField(max_length=50, verbose_name='Email')),
                ('Laboratorypwd', models.CharField(max_length=20, verbose_name='Password')),
                ('Laboratoryfname', models.CharField(default='', max_length=20, verbose_name='Laboratory_Name')),
                ('Laboratorymname', models.CharField(default='', max_length=20, verbose_name='First_Name')),
                ('Laboratorylname', models.CharField(default='', max_length=20, verbose_name='Last_Name')),
                ('Laboratoryaddress', models.CharField(default='', max_length=20, verbose_name='Address')),
                ('Laboratorycity', models.CharField(default='', max_length=20, verbose_name='City')),
                ('Laboratoryarea', models.CharField(default='', max_length=20, verbose_name='Area')),
                ('Laboratorypincode', models.IntegerField(default='', verbose_name='Pincode')),
                ('Laboratorycontactno', models.IntegerField(default='', verbose_name='Contact_No')),
                ('Laboratoryphoto', models.FileField(upload_to='upload', verbose_name='Laboratory certificate')),
            ],
        ),
    ]
