# Generated by Django 5.0.6 on 2024-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0007_laboratoryregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratoryaddress',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratoryarea',
            field=models.CharField(max_length=20, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratorycity',
            field=models.CharField(max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratorycontactno',
            field=models.IntegerField(verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratoryfname',
            field=models.CharField(max_length=20, verbose_name='Laboratory Name'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratorylname',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratorymname',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratoryphoto',
            field=models.FileField(upload_to='upload', verbose_name='Laboratory Certificate'),
        ),
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratorypincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
    ]
