# Generated by Django 5.0.6 on 2024-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0008_alter_laboratoryregister_laboratoryaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryregister',
            name='Laboratoryaddress',
            field=models.TextField(max_length=255, verbose_name='Address'),
        ),
    ]
