# Generated by Django 5.0.6 on 2024-07-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0009_alter_laboratoryregister_laboratoryaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='test_name',
            new_name='Test_name',
        ),
    ]
