# Generated by Django 5.0.6 on 2024-07-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0010_rename_test_name_appointment_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_Test_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Haemoglobin_reference', models.TextField(default='male : 14 - 16g \n Female : 12 - 14 g')),
                ('RBC_reference', models.TextField(default='14 - 16g%')),
                ('PCV_reference', models.TextField(default='35 - 45 %')),
                ('MCV_reference', models.TextField(default='80 - 99 fl')),
                ('MCH_reference', models.TextField(default='28 - 32 pg')),
                ('MCHC_reference', models.TextField(default='30 - 34 %')),
                ('RDW_reference', models.TextField(default='9 - 17 fl')),
                ('Total_WBC_Count_reference', models.TextField(default='4000 - 11000 / cu.mm')),
                ('Neutrophils_reference', models.TextField(default='40 - 75 %')),
                ('Lymphocytes_reference', models.TextField(default='20 - 45 %')),
                ('Eosinophils_reference', models.TextField(default='00 - 06 %')),
                ('Monocytes_reference', models.TextField(default='00 - 10 %')),
                ('Basophils_reference', models.TextField(default='00 - 01 %')),
                ('Platelet_Count_reference', models.TextField(default='150000 - 450000 / cu.mm')),
            ],
        ),
        migrations.RemoveField(
            model_name='test_category',
            name='lname',
        ),
        migrations.AddField(
            model_name='test_category',
            name='l_name',
            field=models.CharField(default='', max_length=200, verbose_name='Lab Assistance Name'),
        ),
        migrations.AlterField(
            model_name='test_category',
            name='Test_name',
            field=models.CharField(default='', max_length=200, verbose_name='Blood Test Name'),
        ),
        migrations.AlterField(
            model_name='test_category',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='test_category',
            name='lab_name',
            field=models.CharField(default='', max_length=200, verbose_name='Lab Name'),
        ),
        migrations.AlterField(
            model_name='test_category',
            name='patientname',
            field=models.CharField(default='', max_length=200, verbose_name='Patient Name'),
        ),
    ]
